/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file is unmodified from its original version developed by Acryl Data, Inc.,
 * and is now included as part of a repository maintained by the National Digital Twin Programme.
 * All support, maintenance and further development of this code is now the responsibility
 * of the National Digital Twin Programme.
 */

interface Capability {
    capability: string;
    description: string;
    supported: boolean;
}

interface PluginDetails {
    capabilities: Capability[];
    classname: string;
    platform_id: string;
    platform_name: string;
    support_status: string;
}

// this type is based off of the type in metadata-ingestion/src/datahub/ingestion/autogenerated/connector_registry/*.json
interface ConnectorRegistry {
    generated_by: string;
    plugin_details: Record<string, PluginDetails>;
}

// Export types for use in other files
export type { ConnectorRegistry, PluginDetails, Capability };
