# SPDX-License-Identifier: Apache-2.0
#
# © Crown Copyright 2025. This work has been developed by the National Digital Twin
# Programme and is legally attributed to the Department for Business and Trade (UK) as the governing
# entity

apiVersion: v1
kind: Secret
metadata:
  name: airflow-webserver-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  webserver-secret-key: {{ .Values.airflow.webserverSecretKey | default "CHANGE_ME_RANDOM_STRING_32_CHARS" | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-connections
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  AIRFLOW_CONN_HYDRO_POSTGRES: "postgresql://{{ .Values.airflow.connections.postgres.user }}:{{ .Values.airflow.connections.postgres.password }}@{{ .Values.airflow.connections.postgres.host }}:{{ .Values.airflow.connections.postgres.port }}/{{ .Values.airflow.connections.postgres.database }}"
  {{- if .Values.airflow.connections.datahub.enabled }}
  AIRFLOW_CONN_DATAHUB_REST: "http://{{ .Values.airflow.connections.datahub.host }}:{{ .Values.airflow.connections.datahub.port }}"
  {{- end }}
