/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * © Crown Copyright 2025. This work has been developed by the National Digital Twin
 * Programme and is legally attributed to the Department for Business and Trade (UK) as the governing
 * entity
 */
import digitalTwinColours from '@conf/theme/colorThemes/digitalTwin';
import { Theme } from '@conf/theme/types';

const themeDigitalTwinV1: Theme = {
    id: 'themeDigitalTwinV1',
    colors: digitalTwinColours,
    styles: {
        'primary-color': '#533FD1',
        'primary-color-dark': '#5C3FD1',
        'primary-color-light': '#ece9f8',
        'layout-header-color': '#434343',
        'body-background': `linear-gradient(180deg, ${digitalTwinColours.bgGradientTop} 0%, ${digitalTwinColours.bgGradientBottom} 100%)`,
        'content-background': digitalTwinColours.bg,
        'border-color-base': '#ececec',
        'homepage-background-upper-fade': '#FFFFFF',
        'homepage-background-lower-fade': '#FFFFFF',
        'homepage-text-color': '#434343',
        'box-shadow': '0px 0px 30px 0px rgb(239 239 239)',
        'box-shadow-hover': '0px 1px 0px 0.5px rgb(239 239 239)',
        'box-shadow-navbar-redesign': '0 0 6px 0px rgba(93, 102, 139, 0.20)',
        'border-radius-navbar-redesign': '12px',
        'highlight-color': '#ece9f8',
        'highlight-border-color': '#07878180',
        'nav-item-text': digitalTwinColours.navItemText,
        'nav-item-hover': digitalTwinColours.navItemHover,
        'icon-selected': digitalTwinColours.iconSelected,
        'logo-text-size': '24px',
        'solid-button-bg-color': digitalTwinColours.solidButtonBgColor,
        'solid-button-text-color': digitalTwinColours.solidButtonTextColor,
        'solid-button-hover-color': digitalTwinColours.solidButtonHoverColor,
        'outline-button-text-color': digitalTwinColours.outlineButtonTextColor,
        'outline-button-border-color': digitalTwinColours.outlineButtonBorderColor,
        'outline-button-hover-text-color': digitalTwinColours.outlineButtonHoverTextColor,
        'outline-button-hover-border-color': digitalTwinColours.outlineButtonHoverBorderColor,
        'segmented-button-text-color': digitalTwinColours.segmentedButtonTextColor,
        'segmented-button-border-color': digitalTwinColours.segmentedButtonBorderColor,
        'segmented-button-hover-color': digitalTwinColours.segmentedButtonHoverColor,
        'segmented-button-focus-border-color': digitalTwinColours.segmentedButtonFocusBorderColor,
        'segmented-button-selected-bg-color': digitalTwinColours.segmentedButtonSelectedBgColor,
        'segmented-button-selected-text-color': digitalTwinColours.segmentedButtonSelectedTextColor,
        'action-button-text-color': digitalTwinColours.actionButtonTextColor,
        'action-button-border-color': digitalTwinColours.actionButtonBorderColor,
        'action-button-hover-color': digitalTwinColours.actionButtonHoverColor,
        'action-button-focus-border-color': digitalTwinColours.actionButtonFocusBorderColor,
        'action-button-focus-text-color': digitalTwinColours.actionButtonFocusTextColor,
        'toggle-off-bg-color': digitalTwinColours.toggleOffBgColor,
        'toggle-off-dot-color': digitalTwinColours.toggleOffDotColor,
        'toggle-on-bg-color': digitalTwinColours.toggleOnBgColor,
        'toggle-on-dot-color': digitalTwinColours.toggleOnDotColor,
        'toggle-label-color': digitalTwinColours.toggleLabelColor,
        'tab-text-color': digitalTwinColours.tabTextColor,
        'tab-hover-bg-color': digitalTwinColours.tabHoverBgColor,
        'tab-selected-text-color': digitalTwinColours.tabSelectedTextColor,
        'tab-hover-underline-color': digitalTwinColours.tabHoverUnderlineColor,
        'tab-selected-underline-color': digitalTwinColours.tabSelectedUnderlineColor,
        'lineage-arrow-icon-color': digitalTwinColours.lineageArrowIconColor,
        'lineage-arrow-hover-bg-color': digitalTwinColours.lineageArrowHoverBgColor,
        'lineage-arrow-border-color': digitalTwinColours.lineageArrowBorderColor,
        'lineage-node-border-color': digitalTwinColours.lineageNodeBorderColor,
        'lineage-node-title-color': digitalTwinColours.lineageNodeTitleColor,
        'lineage-node-selected-border-color': digitalTwinColours.lineageNodeSelectedBorderColor,
        'columns-button-text-color': digitalTwinColours.columnsButtonTextColor,
        'columns-button-hover-color': digitalTwinColours.columnsButtonHoverColor,
        'lineage-home-badge-bg-color': digitalTwinColours.lineageHomeBadgeBgColor,
        'lineage-home-badge-text-color': digitalTwinColours.lineageHomeBadgeTextColor,
        'dropdown-menu-item-text-color': digitalTwinColours.dropdownMenuItemTextColor,
        'dropdown-menu-item-hover-color': digitalTwinColours.dropdownMenuItemHoverColor,
        'search-bar-border-color': digitalTwinColours.searchBarBorderColor,
        'search-bar-hover-border-color': digitalTwinColours.searchBarHoverBorderColor,
        'search-bar-focus-border-color': digitalTwinColours.searchBarFocusBorderColor,
        'pagination-text-color': digitalTwinColours.paginationTextColor,
        'pagination-hover-bg-color': digitalTwinColours.paginationHoverBgColor,
        'pagination-selected-bg-color': digitalTwinColours.paginationSelectedBgColor,
        'pagination-selected-text-color': digitalTwinColours.paginationSelectedTextColor,
        'pagination-disabled-text-color': digitalTwinColours.paginationDisabledTextColor,
        'action-chip-border-color': digitalTwinColours.actionChipBorderColor,
        'action-chip-hover-border-color': digitalTwinColours.actionChipHoverBorderColor,
        'action-chip-hover-bg-color': digitalTwinColours.actionChipHoverBgColor,
        'action-chip-text-color': digitalTwinColours.actionChipTextColor,
        'filter-chip-bg-color': digitalTwinColours.filterChipBgColor,
        'filter-chip-text-color': digitalTwinColours.filterChipTextColor,
    },
    assets: {
        logoUrl: 'assets/logos/data-catalogue-logo.svg',
    },
    content: {
        title: 'Digital Twin Data Catalogue',
        search: {
            searchbarMessage: 'Find tables, dashboards, people, and more',
        },
        menu: {
            items: [
                {
                    label: 'DataHub Project',
                    path: 'https://docs.datahub.com',
                    shouldOpenInNewTab: true,
                    description: 'Explore DataHub Project website',
                },
                {
                    label: 'DataHub GitHub',
                    path: 'https://github.com/linkedin/datahub',
                    shouldOpenInNewTab: true,
                },
            ],
        },
    },
};

export default themeDigitalTwinV1;
