/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * © Crown Copyright 2025. This work has been developed by the National Digital Twin
 * Programme and is legally attributed to the Department for Business and Trade (UK) as the governing
 * entity
 */
import colors from '@conf/theme/colorThemes/color';
import ColorTheme from '@conf/theme/colorThemes/types';

const digitalTwinColours: ColorTheme = {
    bg: colors.ghostWhite,
    bgSurface: colors.gray400,
    bgSurfaceNewNav: colors.gray200,
    bgSurfaceDarker: colors.gray100,
    bgSurfaceBrand: colors.violet0,
    bgSurfaceBrandHover: colors.violet200,
    buttonSurfaceBrandHover: colors.violet800,
    bgDisabled: colors.gray400,
    bgSurfaceError: colors.red0,
    bgSurfaceErrorHover: colors.wine100,
    bgSurfaceInfo: colors.blue0,
    bgSurfaceInformationHover: colors.blue300,
    bgSurfaceSuccess: colors.mudgreen0,
    bgSurfaceSuccessHover: colors.green100,
    bgSurfaceWarning: colors.yellow0,
    bgSurfaceWarningHover: colors.yellow200,
    bgHover: colors.gray400,
    bgGradientTop: colors.delftBlue500,
    bgGradientBottom: colors.eerieBlack,
    text: colors.gray800,
    textSecondary: colors.gray700,
    textTertiary: colors.gray600,
    textBrand: colors.violet600,
    textBrandOnBgFill: colors.gray0,
    textDisabled: colors.gray600,
    textError: colors.red300,
    textInformation: colors.blue700,
    textSuccess: colors.green300,
    textWarning: colors.yellow800,
    hyperlinks: colors.violet600,
    icon: colors.gray600,
    iconBrand: colors.violet500,
    iconError: colors.red100,
    iconInformation: colors.blue600,
    iconSuccess: colors.green200,
    iconWarning: colors.yellow700,
    iconSelected: colors.dtAccentYellow,
    buttonFillBrand: colors.violet600,
    buttonFillFocus: colors.violet600,
    buttonSurfaceBrandFocus: colors.violet200,
    buttonSurfaceSecondaryHover: colors.violet100,
    radioButtonBorder: colors.gray600,
    radioButtonDotFill: colors.gray0,
    radioButtonDotDisabled: colors.gray500,
    avatarBorderBrand: colors.violet100,
    avatarBorderInformation: colors.blue200,
    border: colors.gray100,
    borderBrand: colors.violet600,
    borderBrandFocused: colors.violet400,
    borderBrandInverse: colors.violet0,
    borderDisabled: colors.antiFlashWhite,
    borderInformation: colors.blue700,
    borderInformationInverse: colors.blue0,
    borderError: colors.red300,
    borderSuccess: colors.green300,
    borderWarning: colors.yellow800,
    chartsWineHigh: colors.wine600,
    chartsWineMedium: colors.wine400,
    chartsWineLow: colors.wine200,
    chartsWineBase: colors.wine200,
    chartsPinkHigh: colors.pink300,
    chartsPinkMedium: colors.pink200,
    chartsPinkLow: colors.pink100,
    chartsPinkBase: colors.pink0,
    chartsSeafoamHigh: colors.seafoam300,
    chartsSeafoamMedium: colors.seafoam200,
    chartsSeafoamLow: colors.seafoam100,
    chartsSeafoamBase: colors.seafoam0,
    chartsTangerineHigh: colors.tangerine300,
    chartsTangerineMedium: colors.tangerine200,
    chartsTangerineLow: colors.tangerine100,
    chartsTangerineBase: colors.tangerine0,
    chartsOliveHigh: colors.darkgreen300,
    chartsOliveMedium: colors.darkgreen200,
    chartsOliveLow: colors.darkgreen100,
    chartsOliveBase: colors.darkgreen0,
    chartsBlueHigh: colors.cyan300,
    chartsBlueMedium: colors.cyan200,
    chartsBlueLow: colors.cyan100,
    chartsBlueBase: colors.cyan00,
    chartsGreenHigh: colors.mudgreen600,
    chartsGreenMedium: colors.mudgreen400,
    chartsGreenLow: colors.mudgreen200,
    chartsGreenBase: colors.mudgreen100,
    chartsBrandContrast: '#2200F9FF',
    chartsBrandHigh: colors.violet600,
    chartsBrandMedium: colors.violet500,
    chartsBrandLow: colors.violet300,
    chartsBrandBase: colors.violet200,
    chartsHeatmapHigh: colors.violet900,
    chartsHeatmapMedium: colors.violet500,
    chartsHeatmapLow: colors.violet200,
    chartsHeatmapBase: colors.gray100,
    chartsBrandHighAlpha: '#2200F999',
    chartsBrandMediumAlpha: '#917FFF99',
    chartsBrandLowAlpha: '#B0A7EA99',
    chartsBrandBaseAlpha: '#CAC3F166',
    chartsInformationHigh: colors.blue700,
    navBgGradientTop: '#705EE40A',
    navBgGradientBottom: '#533FD100',
    navItemText: colors.gray0,
    navItemHover: colors.delftBlue500,
    chartsInformationMedium: colors.blue600,
    chartsInformationLow: colors.blue400,
    chartsInformationBase: colors.blue300,
    tagsCoralBg: colors.pink100,
    tagsCoralBorder: colors.pink200,
    tagsCoralText: colors.pink400,
    tagsBrandBg: colors.violet0,
    tagsBrandBorder: colors.violet200,
    tagsBrandText: colors.violet600,
    tagsAccentBg: colors.blue0,
    tagsAccentBorder: colors.blue300,
    tagsAccentText: colors.blue700,
    tagsTangerineBg: colors.tangerine0,
    tagsTangerineBorder: colors.tangerine100,
    tagsTangerineText: colors.tangerine300,
    tagsSeafoamBg: colors.seafoam0,
    tagsSeafoamBorder: colors.seafoam100,
    tagsSeafoamText: colors.seafoam300,
    tagsTrueBlueBg: colors.trueblue0,
    tagsTrueBlueBorder: colors.trueblue100,
    tagsTrueBlueText: colors.trueblue300,
    tagsCobaltBlueBg: colors.cobalt0,
    tagsCobaltBlueBorder: colors.cobalt100,
    tagsCobaltBlueText: colors.cobalt300,
    tagsCyanBg: colors.cyan00,
    tagsCyanBorder: colors.cyan100,
    tagsCyanText: colors.cyan300,
    tagsDeepGreenBg: colors.darkgreen0,
    tagsDeepGreenBorder: colors.darkgreen100,
    tagsDeepGreenText: colors.darkgreen300,
    tagsOliveBg: colors.olive0,
    tagsOliveBorder: colors.olive100,
    tagsOliveText: colors.olive300,
    tagsLavenderBg: colors.lavender0,
    tagsLavenderBorder: colors.lavender100,
    tagsLavenderText: colors.lavender300,
    tagsBrownBg: colors.brown0,
    tagsBrownBorder: colors.brown200,
    tagsBrownText: colors.brown300,
    tagsTrueYellowBg: colors.trueyellow0,
    tagsTrueYellowBorder: colors.trueyellow100,
    tagsTrueYellowIcon: colors.trueyellow200,
    tagsTrueYellowText: colors.trueyellow300,

    // Solid Button
    solidButtonBgColor: `linear-gradient(90deg,${colors.delftBlue500} 0% ${colors.steelBlue}} 100%)`,
    solidButtonTextColor: colors.gray0,
    solidButtonHoverColor: `linear-gradient(90deg,${colors.eerieBlack} 0% ${colors.delftBlue500}} 100%)`,

    // Outline/No Outline Buttons
    outlineButtonTextColor: colors.delftBlue300,
    outlineButtonBorderColor: colors.delftBlue300,
    outlineButtonHoverTextColor: colors.delftBlue500,
    outlineButtonHoverBorderColor: colors.delftBlue500,

    // Segmented Button
    segmentedButtonTextColor: colors.delftBlue200,
    segmentedButtonBorderColor: colors.antiFlashWhite,
    segmentedButtonHoverColor: colors.ghostWhite,
    segmentedButtonFocusBorderColor: colors.steelBlue,
    segmentedButtonSelectedBgColor: colors.steelBlue,
    segmentedButtonSelectedTextColor: colors.gray0,

    // Action Button
    actionButtonTextColor: colors.delftBlue300,
    actionButtonBorderColor: colors.antiFlashWhite,
    actionButtonHoverColor: colors.ghostWhite,
    actionButtonFocusBorderColor: colors.steelBlue,
    actionButtonFocusTextColor: colors.steelBlue,

    // Toggle
    toggleOffBgColor: colors.antiFlashWhite,
    toggleOffDotColor: colors.gray0,
    toggleOnBgColor: colors.steelBlue,
    toggleOnDotColor: colors.gray0,
    toggleLabelColor: colors.delftBlue500,

    // Tabs
    tabTextColor: colors.delftBlue200,
    tabHoverBgColor: colors.ghostWhite,
    tabSelectedTextColor: colors.steelBlue,
    tabHoverUnderlineColor: colors.delftBlue200,
    tabSelectedUnderlineColor: colors.steelBlue,

    // Lineage
    lineageArrowIconColor: colors.steelBlue,
    lineageArrowHoverBgColor: colors.ghostWhite,
    lineageArrowBorderColor: colors.ghostWhite,
    lineageNodeBorderColor: colors.antiFlashWhite,
    lineageNodeTitleColor: colors.delftBlue500,
    lineageNodeSelectedBorderColor: colors.steelBlue,
    columnsButtonTextColor: colors.steelBlue,
    columnsButtonHoverColor: colors.ghostWhite,
    lineageHomeBadgeBgColor: colors.steelBlue,
    lineageHomeBadgeTextColor: colors.gray0,

    // Dropdown
    dropdownMenuItemTextColor: colors.delftBlue500,
    dropdownMenuItemHoverColor: colors.ghostWhite,

    // Search
    searchBarBorderColor: colors.antiFlashWhite,
    searchBarHoverBorderColor: colors.delftBlue200,
    searchBarFocusBorderColor: colors.defaultBlue,

    // Pagination
    paginationTextColor: colors.delftBlue500,
    paginationHoverBgColor: colors.ghostWhite,
    paginationSelectedBgColor: colors.ghostWhite,
    paginationSelectedTextColor: colors.steelBlue,
    paginationDisabledTextColor: colors.delftBlue200,

    // Chips
    actionChipBorderColor: colors.antiFlashWhite,
    actionChipHoverBorderColor: colors.ghostWhite,
    actionChipHoverBgColor: colors.antiFlashWhite,
    actionChipTextColor: colors.delftBlue500,
    filterChipBgColor: colors.steelBlue,
    filterChipTextColor: colors.gray0,
};

export default digitalTwinColours;
